//
// Generated file, do not edit! Created by opp_msgc 4.4 from applications/tcpapp/GenericDataPacket.msg.
//

#ifndef _GENERICDATAPACKETA_M_H_
#define _GENERICDATAPACKETA_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API 
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API 
#  endif
#endif

// cplusplus {{
#include "INETDefs.h"
// }}



/**
 * Class generated from <tt>applications/tcpapp/GenericDataPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet GenericDataPacket
 * {
 *     int expectedReplyLength; 
 *     double replyDelay;       
 *     bool serverClose;        
 *                              
 * }
 * </pre>
 */
class INET_API GenericDataPacket : public ::cPacket
{
  protected:
    int expectedReplyLength_var;
    double replyDelay_var;
    bool serverClose_var;
    int src;
    int dest;
    float data;

  private:
    void copy(const GenericDataPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GenericDataPacket&);

  public:
    GenericDataPacket(const char *name=NULL, int kind=0);
    GenericDataPacket(const GenericDataPacket& other);
    virtual ~GenericDataPacket();
    GenericDataPacket& operator=(const GenericDataPacket& other);
    virtual GenericDataPacket *dup() const {return new GenericDataPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getExpectedReplyLength() const;
    virtual void setExpectedReplyLength(int expectedReplyLength);
    virtual double getReplyDelay() const;
    virtual void setReplyDelay(double replyDelay);
    virtual bool getServerClose() const;
    virtual void setServerClose(bool serverClose);
    virtual int getSourceId();
    virtual int getDestId();
    virtual float getData();
    virtual void setSourceId(int);
    virtual void setDestId(int);
    virtual void setData(float);
};

inline void doPacking(cCommBuffer *b, GenericDataPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GenericDataPacket& obj) {obj.parsimUnpack(b);}


#endif // _GENERICDATAPACKET_M_H_
